

python main.py --is_train=False --dataset=ch --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/ch_1223_170630_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --find_overlap=False --tag=nv
python main.py --is_train=False --dataset=ch --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/ch_1223_170630_01 --load_overlapnet=/media/kimby/Data/Polybox/dev/vectornet2/log/overlap/ch_1224_160412_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --tag=ov

python main.py --is_train=False --dataset=kanji --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/kanji_1223_175926_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --find_overlap=False --tag=nv
python main.py --is_train=False --dataset=kanji --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/kanji_1223_175926_01 --load_overlapnet=/media/kimby/Data/Polybox/dev/vectornet2/log/overlap/kanji_1224_183116_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --tag=ov

python main.py --is_train=False --dataset=line --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/line_1224_152055_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --find_overlap=False --tag=nv
python main.py --is_train=False --dataset=line --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/line_1224_152055_01 --load_overlapnet=/media/kimby/Data/Polybox/dev/vectornet2/log/overlap/line_1225_060657_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --tag=ov

python main.py --is_train=False --dataset=baseball --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/baseball_1224_081511_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --find_overlap=False --tag=nv --height=128 --width=128 --neighbor_sample=0.02
python main.py --is_train=False --dataset=baseball --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/baseball_1224_081511_01 --load_overlapnet=/media/kimby/Data/Polybox/dev/vectornet2/log/overlap/baseball_1224_224311_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --tag=ov --height=128 --width=128 --neighbor_sample=0.02

python main.py --is_train=False --dataset=cat --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/cat_1224_103053_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --find_overlap=False --tag=nv --height=128 --width=128 --neighbor_sample=0.02
python main.py --is_train=False --dataset=cat --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/cat_1224_103053_01 --load_overlapnet=/media/kimby/Data/Polybox/dev/vectornet2/log/overlap/cat_1225_011822_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --tag=ov --height=128 --width=128 --neighbor_sample=0.02

python main.py --is_train=False --dataset=multi --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/multi_1224_124657_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --find_overlap=False --tag=nv --height=128 --width=128 --neighbor_sample=0.02
python main.py --is_train=False --dataset=multi --load_pathnet=/media/kimby/Data/Polybox/dev/vectornet2/log/path/multi_1224_124657_01 --load_overlapnet=/media/kimby/Data/Polybox/dev/vectornet2/log/overlap/multi_1225_041801_01 --data_dir=/media/kimby/Data/Polybox/dev/vectornet2/data --log_dir=/media/kimby/Data/Polybox/dev/vectornet2/log --tag=ov --height=128 --width=128 --neighbor_sample=0.02
